version: "3.8"
services:
  mysql:
    image: mysql:8.0.36-bookworm
    container_name: mysql_styleBook
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: style_book
      MYSQL_USER: user_angel
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
